#ifndef __EYRIE_CALL_H__
#define __EYRIE_CALL_H__

#define RUNTIME_SYSCALL_UNKNOWN             1000
#define RUNTIME_SYSCALL_OCALL               1001
#define RUNTIME_SYSCALL_SHAREDCOPY          1002
#define RUNTIME_SYSCALL_ATTEST_ENCLAVE      1003
#define RUNTIME_SYSCALL_GET_SEALING_KEY     1004
#define RUNTIME_SYSCALL_MAIN_ENCLAVE_GET_SLAVE_ENCLAVE_DATA 1005
#define RUNTIME_SYSCALL_SLAVE_ENCLAVE_SET_DATAPTR           1006
#define RUNTIME_SYSCALL_CREATE_GROUP                        1007
#define RUNTIME_SYSCALL_JOIN_GROUP                          1008
#define RUNTIME_SYSCALL_YXSTM_SET_NUMBERBLOCK               1009
#define RUNTIME_SYSCALL_YXSTM_GET_NUMBERBLOCK               1010
#define RUNTIME_SYSCALL_EXIT                1101

#endif  // __EYRIE_CALL_H__
